/**
 * Narrow Cloudflare runtime declarations for this mixed browser/Worker build.
 *
 * `worker-configuration.d.ts` is generated by Wrangler and owns the binding
 * names. Keeping only the runtime surfaces used by this app here avoids the
 * full Workers ambient declarations replacing DOM types such as `Response`.
 */

interface D1Result<T = unknown> {
  success: boolean
  results: Array<T>
  meta: Record<string, unknown>
  error?: string
}

interface D1PreparedStatement {
  bind(...values: Array<unknown>): D1PreparedStatement
  first<T = Record<string, unknown>>(column?: string): Promise<T | null>
  run<T = Record<string, unknown>>(): Promise<D1Result<T>>
  all<T = Record<string, unknown>>(): Promise<D1Result<T>>
  raw<T = unknown>(options?: { columnNames?: boolean }): Promise<Array<T>>
}

interface D1ExecResult {
  count: number
  duration: number
}

interface D1Database {
  prepare(query: string): D1PreparedStatement
  batch<T = unknown>(
    statements: Array<D1PreparedStatement>,
  ): Promise<Array<D1Result<T>>>
  exec(query: string): Promise<D1ExecResult>
}

interface DurableObjectId {
  toString(): string
}

type DurableObjectStub<T> = {
  fetch(request: Request): Promise<Response>
} & Pick<
  T,
  {
    [K in keyof T]: T[K] extends (...args: Array<never>) => Promise<unknown>
      ? K
      : never
  }[keyof T]
>

interface DurableObjectNamespace<T = unknown> {
  idFromName(name: string): DurableObjectId
  get(id: DurableObjectId): DurableObjectStub<T>
  getByName(name: string): DurableObjectStub<T>
}

interface SqlStorageCursor<
  T extends Record<string, unknown>,
> extends Iterable<T> {
  toArray(): Array<T>
  one(): T
  readonly rowsRead: number
  readonly rowsWritten: number
}

interface SqlStorage {
  exec<T extends Record<string, unknown> = Record<string, unknown>>(
    query: string,
    ...bindings: Array<unknown>
  ): SqlStorageCursor<T>
}

interface DurableObjectStorage {
  readonly sql: SqlStorage
  get<T = unknown>(key: string): Promise<T | undefined>
  put<T>(key: string, value: T): Promise<void>
  delete(key: string): Promise<boolean>
}

interface DurableObjectState {
  readonly storage: DurableObjectStorage
  blockConcurrencyWhile<T>(callback: () => Promise<T>): Promise<T>
  acceptWebSocket(webSocket: WebSocket, tags?: Array<string>): void
  getWebSockets(tag?: string): Array<WebSocket>
}

interface WebSocket {
  accept(): void
  serializeAttachment(attachment: unknown): void
  deserializeAttachment<T = unknown>(): T | null
}

interface WebSocketPair {
  readonly 0: WebSocket
  readonly 1: WebSocket
}

declare const WebSocketPair: {
  new (): WebSocketPair
}

interface ResponseInit {
  webSocket?: WebSocket | null
}

interface Response {
  readonly webSocket?: WebSocket | null
}

declare module 'cloudflare:workers' {
  export const env: Cloudflare.Env

  export abstract class DurableObject<TEnv = Cloudflare.Env> {
    protected readonly ctx: DurableObjectState
    protected readonly env: TEnv

    constructor(ctx: DurableObjectState, env: TEnv)

    fetch(request: Request): Response | Promise<Response>
  }
}
