/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 78d9f23b4dc361bc2f3d688225dca103)
interface __BaseEnv_Env {
	AUTH_DB: D1Database;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GITHUB_APP_SLUG: string;
	GITHUB_WEBHOOK_SECRET: string;
	GITHUB_TOKEN_ENCRYPTION_KEY: string;
	REPOSITORY_EVENTS: DurableObjectNamespace<import("./src/server").RepositoryEvents>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "RepositoryEvents";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "GITHUB_APP_SLUG" | "GITHUB_WEBHOOK_SECRET" | "GITHUB_TOKEN_ENCRYPTION_KEY">> {}
}
