/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareRouteImport } from './routes/share'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as ApiGithubEventsRouteImport } from './routes/api.github.events'
import { Route as ApiGithubWebhookRouteImport } from './routes/api.github.webhook'
import { Route as ApiGithubOauthCallbackRouteImport } from './routes/api.github.oauth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubEventsRoute = ApiGithubEventsRouteImport.update({
  id: '/api/github/events',
  path: '/api/github/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubOauthCallbackRoute = ApiGithubOauthCallbackRouteImport.update({
  id: '/api/github/oauth/callback',
  path: '/api/github/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/api/github/events': typeof ApiGithubEventsRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/api/github/events': typeof ApiGithubEventsRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/api/github/events': typeof ApiGithubEventsRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/github/oauth/callback': typeof ApiGithubOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/share'
    | '/p/$projectId'
    | '/api/github/events'
    | '/api/github/webhook'
    | '/api/github/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/share'
    | '/p/$projectId'
    | '/api/github/events'
    | '/api/github/webhook'
    | '/api/github/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/share'
    | '/p/$projectId'
    | '/api/github/events'
    | '/api/github/webhook'
    | '/api/github/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareRoute: typeof ShareRoute
  PProjectIdRoute: typeof PProjectIdRoute
  ApiGithubEventsRoute: typeof ApiGithubEventsRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiGithubOauthCallbackRoute: typeof ApiGithubOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/events': {
      id: '/api/github/events'
      path: '/api/github/events'
      fullPath: '/api/github/events'
      preLoaderRoute: typeof ApiGithubEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/oauth/callback': {
      id: '/api/github/oauth/callback'
      path: '/api/github/oauth/callback'
      fullPath: '/api/github/oauth/callback'
      preLoaderRoute: typeof ApiGithubOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareRoute: ShareRoute,
  PProjectIdRoute: PProjectIdRoute,
  ApiGithubEventsRoute: ApiGithubEventsRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiGithubOauthCallbackRoute: ApiGithubOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
